set(_AMENT_PACKAGE_NAME "imu_reader")
set(imu_reader_VERSION "0.0.0")
set(imu_reader_MAINTAINER "lunabotics <154274810+JBL168@users.noreply.github.com>")
set(imu_reader_BUILD_DEPENDS )
set(imu_reader_BUILDTOOL_DEPENDS "ament_cmake")
set(imu_reader_BUILD_EXPORT_DEPENDS )
set(imu_reader_BUILDTOOL_EXPORT_DEPENDS )
set(imu_reader_EXEC_DEPENDS )
set(imu_reader_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(imu_reader_GROUP_DEPENDS )
set(imu_reader_MEMBER_OF_GROUPS )
set(imu_reader_DEPRECATED "")
set(imu_reader_EXPORT_TAGS)
list(APPEND imu_reader_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
