set(_AMENT_PACKAGE_NAME "joy_controller_cpp")
set(joy_controller_cpp_VERSION "0.0.0")
set(joy_controller_cpp_MAINTAINER "lunabotics <lunabotics@todo.todo>")
set(joy_controller_cpp_BUILD_DEPENDS "rclcpp" "sensor_msgs" "geometry_msgs")
set(joy_controller_cpp_BUILDTOOL_DEPENDS "ament_cmake")
set(joy_controller_cpp_BUILD_EXPORT_DEPENDS "rclcpp" "sensor_msgs" "geometry_msgs")
set(joy_controller_cpp_BUILDTOOL_EXPORT_DEPENDS )
set(joy_controller_cpp_EXEC_DEPENDS "rclcpp" "sensor_msgs" "geometry_msgs")
set(joy_controller_cpp_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(joy_controller_cpp_GROUP_DEPENDS )
set(joy_controller_cpp_MEMBER_OF_GROUPS )
set(joy_controller_cpp_DEPRECATED "")
set(joy_controller_cpp_EXPORT_TAGS)
list(APPEND joy_controller_cpp_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
